### ISSUE TITLE
Merge Strategy for the USEPA version and Feng's (cancelled) Pull Request

### ISSUE THREAD

**Issue by karrowood** [OpenWaterAnalytics/epanet-msx#8]
I have recently worked with the CMake files in Issue #7 (https://github.com/OpenWaterAnalytics/epanet-msx/issues/7) in order to compile and run the USEPA version of the repository which can be found on the epa-upstream-1.1.0 branch.

I then used the same strategy to compile and run the code found in Feng's cancelled pull request. In Feng's version of the code, the reports contain additional water quality information at the bottom of the reports. This information includes the water quality mass balance for different chemicals. It details the Initial Mass, Mass Inflow, Mass Outflow, Mass Reacted, Final Mass, and Mass Ratio.

After successfully running Feng's code, I merged it with the USEPA version and fixed all merge conflicts. I favored Feng's version of the code over the USEPA version with the conflicts to make sure not to mess up any of the additional features. I then made sure it could compile and successfully ran examples.

If wanted, I can create a pull request for this code, including the CMake files and I can create a document with compiling instructions specifically for Windows as I have not had the ability to compile this on Mac or Linux.

**Comment by samhatchett** [comment]
Sounds like a good approach. I've re-opened and merged the PR so that Feng's commits remain intact in the git history, so hopefully that doesn't throw a wrench in this plan. If you could open a PR into `dev` branch that adds CMake files any other diffs from the USEPA distributable code, we will be in good shape for getting community input. I think we will especially want to verify the build tooling on Mac and *nix to make sure the project is nice and clean for anyone who wants to pick it up.

**Comment by samhatchett** [comment]
given no other comments (thanks to @rjanke20 for the thumbs-up!), we will consider this resolved. All other comments and questions should go to the PR.
